# Generated by Django 2.2.1 on 2020-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
