# Generated by Django 2.2.1 on 2020-02-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200128_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='payslip',
            name='other',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpay',
            name='additional',
            field=models.CharField(blank=True, choices=[('Annual Air Ticket', 'Annual Air Ticket'), ('Expense Reimbursement', 'Expense Reimbursement'), ('Bonus', 'Bonus'), ('Overtime/ Holiday Pay', 'Overtime/ Holiday Pay'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpays',
            name='additional',
            field=models.CharField(blank=True, choices=[('Annual Air Ticket', 'Annual Air Ticket'), ('Expense Reimbursement', 'Expense Reimbursement'), ('Bonus', 'Bonus'), ('Overtime/ Holiday Pay', 'Overtime/ Holiday Pay'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_name', to='payroll.CostCenter'),
        ),
    ]
