# Generated by Django 2.2.1 on 2020-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200203_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='employee_unique',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
