# Generated by Django 2.2.1 on 2020-02-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslip_employee_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='designation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpay',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='deduction',
            field=models.CharField(blank=True, choices=[('Housing Loan', 'Housing Loan'), ('Salary Advance', 'Salary Advance'), ('Traffic Fine', 'Traffic Fine'), ('Loan', 'Loan'), ('Unpaid sick leave', 'Unpaid sick leave'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='housing_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='transportation_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processsalary',
            name='Additional_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processsalary',
            name='deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processsalary',
            name='gross_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processsalary',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
