# Generated by Django 2.2.1 on 2020-02-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20200205_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpay',
            name='additional',
            field=models.CharField(blank=True, choices=[('Annual Air Ticket', 'Annual Air Ticket'), ('Expense Reimbursement', 'Expense Reimbursement'), ('Salary Advance', 'Salary Advance'), ('Bonus', 'Bonus'), ('Overtime/ Holiday Pay', 'Overtime/ Holiday Pay'), ('Other', 'Other')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='additionalpays',
            name='additional',
            field=models.CharField(blank=True, choices=[('Annual Air Ticket', 'Annual Air Ticket'), ('Expense Reimbursement', 'Expense Reimbursement'), ('Salary Advance', 'Salary Advance'), ('Bonus', 'Bonus'), ('Overtime/ Holiday Pay', 'Overtime/ Holiday Pay'), ('Other', 'Other')], max_length=60, null=True),
        ),
    ]
