# Generated by Django 2.2.1 on 2020-02-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_employee_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default=['Active'], max_length=10),
        ),
    ]
