# Generated by Django 2.2.1 on 2020-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20200216_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='payment_mothod',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Lulu Exchange', 'Lulu Exchange'), ('Cash', 'Cash')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
