# Generated by Django 2.2.1 on 2020-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20200223_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='payment_mothod',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=['Active'], max_length=10),
        ),
    ]
