# Generated by Django 2.2.1 on 2020-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20200223_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsalary',
            name='employee_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
