# Generated by Django 2.2.1 on 2020-02-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_processsalary_employee_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='agent_id',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bank_ac',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='bank_name_routing',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='employee_unique',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='personal_no_14_digits',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='work_permit_8_digits',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('partial', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=60)),
                ('normal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holiday', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vacation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sick', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lwop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_timesheet', to='payroll.Employee')),
            ],
        ),
    ]
