# Generated by Django 2.2.1 on 2020-03-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auto_20200304_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=60)),
                ('month', models.DateField()),
                ('partial', models.CharField(max_length=60)),
                ('normal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holiday', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vacation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sick', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lwop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Report')),
            ],
        ),
    ]
