# Generated by Django 2.2.1 on 2020-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_processsalary_actual_gross_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lowp_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
