# Generated by Django 2.2.1 on 2020-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20200519_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Lulu Exchange', 'Lulu Exchange'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=15),
        ),
    ]
