# Generated by Django 2.2.1 on 2020-05-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20200520_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
