# Generated by Django 2.2.1 on 2020-06-09 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_auto_20200523_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seha_id', models.CharField(blank=True, max_length=90, null=True)),
                ('zoho_id', models.CharField(blank=True, max_length=90, null=True)),
                ('source', models.CharField(blank=True, max_length=90, null=True)),
                ('source_entity', models.CharField(blank=True, max_length=90, null=True)),
                ('category', models.CharField(blank=True, max_length=90, null=True)),
                ('hiring_status', models.CharField(blank=True, max_length=90, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=90, null=True)),
                ('Passport_no', models.CharField(blank=True, max_length=90, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('licence_authority', models.CharField(blank=True, max_length=90, null=True)),
                ('doh_licence', models.CharField(blank=True, max_length=90, null=True)),
                ('doh_licence_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=15)),
                ('doh_licence_no', models.CharField(blank=True, max_length=90, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=90, null=True)),
                ('licence_issued_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_clinical', to='payroll.Employee')),
            ],
        ),
    ]
