# Generated by Django 2.2.1 on 2020-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20200609_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical',
            name='clinic_exp_in_5_year',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
