# Generated by Django 2.2.1 on 2020-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_clinical_clinic_exp_in_5_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical',
            name='company_email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
