# Generated by Django 2.2.1 on 2020-07-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20200609_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.BooleanField(default=False)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_workpermit', to='payroll.Employee')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_work_permit', to='payroll.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.BooleanField(default=False)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('passport', models.BooleanField(default=False)),
                ('passport_date', models.DateField(blank=True, null=True)),
                ('medical', models.BooleanField(default=False)),
                ('medical_date', models.DateField(blank=True, null=True)),
                ('passport_return', models.BooleanField(default=False)),
                ('passport_return_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_labourcontract', to='payroll.Employee')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_name', to='payroll.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='EidCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.DateField(blank=True, null=True)),
                ('returned', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_eidcollect', to='payroll.Employee')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_eid_collect', to='payroll.Hotel')),
            ],
        ),
    ]
