# Generated by Django 2.2.1 on 2020-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20200728_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborcontract',
            old_name='contract_sign_date',
            new_name='contract_collected_date',
        ),
        migrations.RenameField(
            model_name='workpermit',
            old_name='contract_date',
            new_name='contract_collected_date',
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='contract_collected',
            field=models.BooleanField(default=False),
        ),
    ]
