# Generated by Django 2.2.1 on 2020-07-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_auto_20200728_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Deployed', 'Deployed'), ('Exiting', 'Exiting')], default=['Active'], max_length=10),
        ),
    ]
