# Generated by Django 2.2.1 on 2020-07-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_auto_20200730_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eidcollect',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eidcollect',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
