# Generated by Django 2.2.1 on 2020-07-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20200730_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborcontract',
            old_name='medical',
            new_name='medical_done',
        ),
        migrations.RenameField(
            model_name='laborcontract',
            old_name='passport_collect',
            new_name='passport_collected',
        ),
        migrations.RenameField(
            model_name='laborcontract',
            old_name='passport_return',
            new_name='passport_returned',
        ),
        migrations.RenameField(
            model_name='laborcontract',
            old_name='passport_return_date',
            new_name='passport_returned_date',
        ),
    ]
