# Generated by Django 2.2.1 on 2020-07-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_auto_20200730_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid_received_date', models.DateField(blank=True, null=True)),
                ('collected', models.BooleanField(default=False)),
                ('eid_collected_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_neweid', to='payroll.Employee')),
            ],
        ),
    ]
