# Generated by Django 2.2.1 on 2020-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_neweid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eidcollect',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='laborcontract',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='neweid',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='workpermit',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
