# Generated by Django 2.2.1 on 2020-08-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20200804_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborcontract',
            name='passport_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
