# Generated by Django 2.2.1 on 2020-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_laborcontract_passport_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Deployed', 'Deployed'), ('Exiting', 'Exiting'), ('Resigning', 'Resigning')], default=['Active'], max_length=10),
        ),
    ]
